# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 07:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210225_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creator_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
