# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210226_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
