# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-26 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator_user_id',
            new_name='creator',
        ),
    ]
