# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-01 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_auto_20210228_2005'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('post_id', 'user_id')]),
        ),
    ]
